"""Agregando rol a User

Revision ID: 135134228079
Revises: f53ffc4d214e
Create Date: 2025-04-04 11:25:00.447244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135134228079'
down_revision = 'f53ffc4d214e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.String(length=10), nullable=False))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('rol')

    # ### end Alembic commands ###
