"""Agregar campos: participantes, genero, tipo_evento, organizacion, imagen

Revision ID: 13e1229ab1ae
Revises: 8075bef587c2
Create Date: 2025-06-17 10:02:47.045570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e1229ab1ae'
down_revision = '8075bef587c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participantes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('genero', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('tipo_evento', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('organizacion', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('imagen', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.drop_column('imagen')
        batch_op.drop_column('organizacion')
        batch_op.drop_column('tipo_evento')
        batch_op.drop_column('genero')
        batch_op.drop_column('participantes')

    # ### end Alembic commands ###
