"""Agregar responsable y motivo_rechazo con columnas nulas

Revision ID: 8075bef587c2
Revises: 85d9291b0923
Create Date: 2229-01-01 00:51:11.370188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8075bef587c2'
down_revision = '85d9291b0923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsable', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('motivo_rechazo', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.drop_column('motivo_rechazo')
        batch_op.drop_column('responsable')

    # ### end Alembic commands ###
