"""Agregar campo lugar a Evento

Revision ID: 85d9291b0923
Revises: c23484d1853d
Create Date: 2025-04-09 12:34:16.295340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d9291b0923'
down_revision = 'c23484d1853d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lugar', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.drop_column('lugar')

    # ### end Alembic commands ###
