"""Agregar usuario_id a Evento

Revision ID: c23484d1853d
Revises: 135134228079
Create Date: 2025-04-09 11:29:00.088000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23484d1853d'
down_revision = '135134228079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_evento_usuario', 'user', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.drop_constraint('fk_evento_usuario', type_='foreignkey')
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
